---
title: "mbruner3_1.r"
author: "Mark Bruner"
date: "9/11/2020"
output:
  pdf_document: default
  html_document: default
---
```{r echo = FALSE}
rm(list=ls())
```

## Reference
Data is taken from http://faculty.marshall.usc.edu/gareth-james/ISL/College.csv

```{r}
library(tidyverse)
library(ISLR)
library(caret)
```

```{r}
college <- read_csv("college.csv", col_types = "cciiiddiidddddddddd")
head(college)
tail(college)
str(college)
```


```{r}
college %>%  
  rename("College.Name" = "X1")
```

```{r}
summary(college)
colMeans(is.na(college))
```
**Data Summary**
No missing data in the dataset. 


##Qualitative Descriptive Statistics & Transformation of Data 
```{r}
library(tidyverse)
private <- table(college$Private)
private_df <- as.data.frame(private)
private_df <- rename(private_df, "Private" = "Var1")
private_percent <- private_df$Freq/sum(private_df$Freq)
private_df_percent <- add_column(private_df, private_percent)
private_df_percent <- rename(private_df_percent, "Percent" = "private_percent")
private_df_percent
```
## Scatterplot: Multi-variable
Created a scatterplot of the two variable Applications and Acceptance in the College Data Set.
```{r}
college %>% 
  ggplot(mapping = aes(x = Apps, y = Accept, col = Private, shape = Private)) + geom_point()
```

# Single Variable Visualization

```{r}
college %>% 
  ggplot(mapping = aes(x = Private)) + 
  geom_histogram(stat = "Count", fill = "light blue", col = "skyblue")
```