---
title: "mbruner3_3"
author: "Mark Bruner"
date: "10/4/2020"
output: pdf_document
---

# Libraries needed for this assignment.
```{r}
library(tidyverse)
library(lubridate)
library(caret)
library(ISLR)
library(e1071)
library(fastDummies)
```
# Imported dataset.
```{r}
flight_delays <- read_csv("FlightDelays.csv", col_types = "fffficfffffff")
flight_delays$FL_DATE <- mdy(flight_delays$FL_DATE) # converted the FL_DATE column to date format.

colMeans(is.na(flight_delays)) # no missing data.

head(flight_delays)
```

```{r}
flight_delays <- flight_delays[, c(1, 2, 4, 8, 10, 13)] # created df with predictors.


index_train <- createDataPartition(flight_delays$DAY_WEEK, p = .6, list = FALSE)
flight_train <- flight_delays[index_train, ] 
flight_test <- flight_delays[-index_train, ]
head(flight_delays)
```

```{r}
naive_model <- naiveBayes(flight_delays$`Flight Status` ~flight_delays$CRS_DEP_TIME + flight_delays$CARRIER + flight_delays$DEST + flight_delays$ORIGIN + flight_delays$DAY_WEEK, data = flight_train)
naive_model
```

```{r}
predicted_flight_labels <- predict(naive_model, flight_test)

library(gmodels)

CrossTable(x = flight_test$`Flight Status`, y = predicted_flight_labels, prop.chisq = FALSE)
```

```{r}
predicted_flight_labels2 <- predict(naive_model, flight_test, type = "raw")
head(predicted_flight_labels2)
```
```{r}
library(pROC)
```

